[package]
name = "smart-query"
description = "Robust approach to queries for CronCat"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
schemars = "0.8"
serde = { workspace = true, default-features = false, features = ["derive"] }
cosmwasm-std = { workspace = true, features = ["staking", "stargate"] }
serde-cw-value = { workspace = true }
generic-query = { workspace = true }
thiserror = { workspace = true }
