[package]
name = "cw-rules-core"
description = "CronCat rules core logic for tasks that require conditions"
license = "MIT OR Apache-2.0"
version = "0.1.2"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
schemars = "0.8"
serde = { workspace = true, default-features = false, features = ["derive"] }
cosmwasm-std = { workspace = true, features = ["staking", "stargate"] }
serde-cw-value = { workspace = true }
# For some reason it tries to deploy cw_core here
# voting = { version = "0.2.0", default-features = false, git = "https://github.com/DA0-DA0/dao-contracts" }
generic-query = { workspace = true }
smart-query = { workspace = true }
cw20 = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
rusty-hook = { workspace = true }
