[package]
name = "cw-croncat-core"
description = "CronCat core logic allowing automated scheduling of transactions and IFTTT for the interchain"
license = "MIT OR Apache-2.0"
version = "0.1.5"
edition = "2021"

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.5
"""

[dependencies]
cosmwasm-std = { workspace = true, features = ["staking", "stargate"] }
cw-rules-core = { workspace = true, path = "../cw-rules-core" }
generic-query = { workspace = true, path = "../generic-query" }
cw-storage-plus = { workspace = true }
cron_schedule = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true }
hex = { workspace = true, default-features = false }
sha2 = { workspace = true, default-features = false }
serde-cw-value = { workspace = true }
serde-json-wasm = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
cw-multi-test = { workspace = true, features = ["staking"] }
cw20-base = { workspace = true, features = ["library"] }
rusty-hook = { workspace = true }
