[package]
name = "generic-query"
description = "Generalizing ways to query and order"
license = "MIT OR Apache-2.0"
version = "0.1.1"
edition = { workspace = true }

[dependencies]
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
cosmwasm-std = { workspace = true, features = ["staking", "stargate"] }
serde-cw-value = { workspace = true }
